// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: model/event.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// イベント種別
type EventType int32

const (
	// 不明なイベント
	EventType_UNKNOWN EventType = 0
	// メッセージ受信
	EventType_MESSAGE EventType = 1
	// ステータス変更
	EventType_STATUS EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "MESSAGE",
		2: "STATUS",
	}
	EventType_value = map[string]int32{
		"UNKNOWN": 0,
		"MESSAGE": 1,
		"STATUS":  2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_model_event_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_model_event_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_model_event_proto_rawDescGZIP(), []int{0}
}

// イベント
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// イベントID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// イベントデータ
	//
	// Types that are assignable to Data:
	//	*Event_Message
	//	*Event_Status
	Data isEvent_Data `protobuf_oneof:"data"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_model_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_model_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (m *Event) GetData() isEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Event) GetMessage() *MessageReceiveEvent {
	if x, ok := x.GetData().(*Event_Message); ok {
		return x.Message
	}
	return nil
}

func (x *Event) GetStatus() *ChangeStatusEvent {
	if x, ok := x.GetData().(*Event_Status); ok {
		return x.Status
	}
	return nil
}

type isEvent_Data interface {
	isEvent_Data()
}

type Event_Message struct {
	Message *MessageReceiveEvent `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

type Event_Status struct {
	Status *ChangeStatusEvent `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

func (*Event_Message) isEvent_Data() {}

func (*Event_Status) isEvent_Data() {}

// メッセージ受信イベント
//
// メッセージの受信イベントを表します。
type MessageReceiveEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// イベント種別（MESSAGE 固定）
	Type EventType `protobuf:"varint,1,opt,name=type,proto3,enum=api.EventType" json:"type,omitempty"`
	// メッセージ
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// 送信者ユーザーID
	UserId int32 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 送信日時
	PublishAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=publish_at,json=publishAt,proto3" json:"publish_at,omitempty"`
}

func (x *MessageReceiveEvent) Reset() {
	*x = MessageReceiveEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageReceiveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReceiveEvent) ProtoMessage() {}

func (x *MessageReceiveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_model_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReceiveEvent.ProtoReflect.Descriptor instead.
func (*MessageReceiveEvent) Descriptor() ([]byte, []int) {
	return file_model_event_proto_rawDescGZIP(), []int{1}
}

func (x *MessageReceiveEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_UNKNOWN
}

func (x *MessageReceiveEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageReceiveEvent) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageReceiveEvent) GetPublishAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishAt
	}
	return nil
}

// ステータス変更イベント
//
// ユーザーのステータス変更イベントを表します。
type ChangeStatusEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// イベント種別（STATUS 固定）
	Type EventType `protobuf:"varint,1,opt,name=type,proto3,enum=api.EventType" json:"type,omitempty"`
	// ユーザーID
	UserId int32 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 変更後ステータス
	Status UserStatus `protobuf:"varint,3,opt,name=status,proto3,enum=api.UserStatus" json:"status,omitempty"`
}

func (x *ChangeStatusEvent) Reset() {
	*x = ChangeStatusEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStatusEvent) ProtoMessage() {}

func (x *ChangeStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_model_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStatusEvent.ProtoReflect.Descriptor instead.
func (*ChangeStatusEvent) Descriptor() ([]byte, []int) {
	return file_model_event_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeStatusEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_UNKNOWN
}

func (x *ChangeStatusEvent) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangeStatusEvent) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_ONLINE
}

var File_model_event_proto protoreflect.FileDescriptor

var file_model_event_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x05,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x06, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa1, 0x01, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x39,
	0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x74, 0x22, 0x79, 0x0a, 0x11, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x22,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2a, 0x31, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x02, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x6b, 0x61, 0x35, 0x32, 0x31, 0x2f, 0x63, 0x68,
	0x61, 0x74, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_event_proto_rawDescOnce sync.Once
	file_model_event_proto_rawDescData = file_model_event_proto_rawDesc
)

func file_model_event_proto_rawDescGZIP() []byte {
	file_model_event_proto_rawDescOnce.Do(func() {
		file_model_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_event_proto_rawDescData)
	})
	return file_model_event_proto_rawDescData
}

var file_model_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_model_event_proto_goTypes = []interface{}{
	(EventType)(0),                // 0: api.EventType
	(*Event)(nil),                 // 1: api.Event
	(*MessageReceiveEvent)(nil),   // 2: api.MessageReceiveEvent
	(*ChangeStatusEvent)(nil),     // 3: api.ChangeStatusEvent
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(UserStatus)(0),               // 5: api.UserStatus
}
var file_model_event_proto_depIdxs = []int32{
	2, // 0: api.Event.message:type_name -> api.MessageReceiveEvent
	3, // 1: api.Event.status:type_name -> api.ChangeStatusEvent
	0, // 2: api.MessageReceiveEvent.type:type_name -> api.EventType
	4, // 3: api.MessageReceiveEvent.publish_at:type_name -> google.protobuf.Timestamp
	0, // 4: api.ChangeStatusEvent.type:type_name -> api.EventType
	5, // 5: api.ChangeStatusEvent.status:type_name -> api.UserStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_model_event_proto_init() }
func file_model_event_proto_init() {
	if File_model_event_proto != nil {
		return
	}
	file_model_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_model_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageReceiveEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeStatusEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_model_event_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Event_Message)(nil),
		(*Event_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_event_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_event_proto_goTypes,
		DependencyIndexes: file_model_event_proto_depIdxs,
		EnumInfos:         file_model_event_proto_enumTypes,
		MessageInfos:      file_model_event_proto_msgTypes,
	}.Build()
	File_model_event_proto = out.File
	file_model_event_proto_rawDesc = nil
	file_model_event_proto_goTypes = nil
	file_model_event_proto_depIdxs = nil
}
